name: Install Dependencies
description: Install Dependencies
inputs:
  package-manager:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: ${{ inputs.package-manager }}
    
    - name: Install dependencies
      shell: bash
      run: npm install