name: Deployment - Reuseable Workflow
on: 
  workflow_call:
    inputs:
      kubectl-version:
        required: false
        default: 'v1.26.0'
        type: string
      k8s_path:
        required: true
        type: string
      namespace:
        type: string
        required: true
      replicas:
        required: false
        default: 1
        type: number
      image:
        required: true
        type: string
    secrets:
      mongo-uri:
        required: true

jobs:
  reuse-deploy:
    runs-on: [self-hosted, macOS, ARM64]
    outputs:
      APP_INGRESS_URL: ${{ steps.get-ingress-url.outputs.APP_INGRESS_URL }}
    steps:
      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ inputs.kubectl-version }}

      
      - name: Replace tokens in manifests
        uses: cschleiden/replace-tokens@v1
        with: 
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: ${{ inputs.k8s_path }}/*.yaml
        env:
          NAMESPACE: ${{ inputs.namespace }}
          REPLICAS: ${{ inputs.replicas }}
          K8S_IMAGE: ${{ inputs.image }}
          INGRESS_IP: 127.0.0.1
      
      - name: Verify replaced manifests
        run: cat ${{ inputs.k8s_path }}/*.yaml

      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ inputs.namespace }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ secrets.mongo-uri }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -
      
      - name: Deploy to Dev Environment
        run: |
          kubectl apply -f ${{ inputs.k8s_path }}

      - name: Set App Ingress Host Url
        id: get-ingress-url
        run: |
          echo "APP_INGRESS_URL=$(kubectl -n ${{ inputs.namespace }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_OUTPUT
