name: Solar System Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      mongo-db:
        image: mongo
        ports:
          - 27017:27017
    env:
        MONGO_URI: mongodb://localhost:27017/superData
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies    
        run: npm install
  

      - name: Run tests
        run: npm test
      
      - name: Upload test results
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: test-results.xml
  coverage-test:
    runs-on: ubuntu-latest
    container:
      image: node:18

    services:
      mongo-db:
        image: mongo

    env:
        MONGO_URI: mongodb://mongo-db:27017/superData

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install


      - name: Run coverage tests
        run: npm run coverage
        continue-on-error: true
      
      - name: Upload coverage results
        uses: actions/upload-artifact@v7
        with:
          name: coverage-results
          path: coverage
          retention-days: 5

  container:
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    permissions:
      packages: write
    runs-on: [self-hosted, macOS, ARM64]
    needs: [unit-test, coverage-test]
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
     
      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          buildx-version: latest
          context: .
          push: false
          tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
      
      - name: Docker Image Test
        run: |
          docker images
          docker run --name solar-system-${{ github.run_id }}-${{ github.run_attempt }} -d \
            -p 3000:3000 \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

          for i in {1..10}; do
            if curl --fail --silent http://127.0.0.1:3000/live | grep -q live; then
              exit 0
            fi
            sleep 2
          done

      - name: Clean up test container
        if: always()
        run: docker rm --force solar-system-${{ github.run_id }}-${{ github.run_attempt }} || true

      - name: Docker Push
        uses: docker/build-push-action@v5
        with:
          buildx-version: latest
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
      
  deploy:
    needs: container
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'
      
      # - name: Save Ingress IP
      #   id: ingress
      #   run: |
      #     echo "INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller \
      #       -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      
      - name: Replace tokens in manifests
        uses: cschleiden/replace-tokens@v1
        with: 
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: kubernetes/development/*.yaml
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: 127.0.0.1
      
      - name: Verify replaced manifests
        run: cat kubernetes/development/*.yaml

      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -
      
      - name: Deploy to Dev Environment
        run: |
          kubectl apply -f kubernetes/development
